---
title: "R Notebook: Data Frames and Vectors"
output: html_notebook
author: "Sweta Sharma"
Date: "09/13/2019"
---

# Given data 

```{r}
gender = c("M","F","M","F", "F","M","F")
names(gender)=c("Bob","Susan","Jim","Mary","Jane","Tim","Nicole") 
weight <- c(60,72,57,90,95,72)
height <- c(1.75,1.8,1.65,1.9,1.74,1.91)
weight = c(weight, 86)
height = c(height, NA)
```
## Creating Dataframe

```{r}
GHWData = data.frame(gender,height,weight)
GHWData
```
### 1.People with either weights below 70 or height below 1.70 and not NA

```{r}
# Using condition GHWData$weight < 70 for weight clause, GHWData$height < 1.70 for height clause and !is.na(GHWData$height) to avoid the NA in height

GHWData[(GHWData$weight < 70 | GHWData$height < 1.70) & !is.na(GHWData$height),] 

```
### 2. Added column named bmi that is weight/height ^ 2

```{r}
GHWData$bmi <- weight/height ^ 2
GHWData

```
### 3.Those with NA in any column

```{r}
GHWData[is.na(GHWData$height) | is.na(GHWData$weight) | is.na(GHWData$bmi),]
```
### 4.Those with NA in all the columns

```{r}
GHWData[is.na(GHWData$height) & is.na(GHWData$weight) & is.na(GHWData$bmi),]
```

### 5. Filter out rows with NA in any column,then sort by people names in an increasing order

```{r}

#create variable, sorted_row_names, to get rows that dont have any NA

sorted_row_names <-sort(rownames(GHWData[!is.na(GHWData$height) & !is.na(GHWData$weight) & !is.na(GHWData$bmi), ]))

# Display all the columns of the dataframe for the sorted rows

GHWData[sorted_row_names,]


```

